### ISSUE TITLE
export default waitForElementTransition; error

### ISSUE THREAD

**Issue by Jerit3787** [markcellus/wait-for-element-transition#213] opened 2021-02-26 13:00 UTC
Hello,
may I know why I do get this error from the lines on your code?

Error : Uncaught SyntaxError: Unexpected token 'export'
export default waitForElementTransition;

**Comment by markcellus** [comment] 2021-02-27 10:44
Which browser and OS version?

**Comment by Jerit3787** [comment] 2021-02-28 02:55
Microsoft Edge 88 with Windows 10 Home 20H2 installed

**Comment by markcellus** [comment] 2021-02-28 15:24
Thanks for that info. I'll check that browser specifically since I'm not seeing any issues on non-microsoft browsers I've checked. But before I do that, can you also tell me exactly what element you're passing to `waitForElementTransition`? And what css properties are being applied that need waiting?

**Comment by Jerit3787** [comment] 2021-02-28 19:07
oh I was passing 'div' to the function and its was applying changes to the width. So, I wanted to wait for the transition to finished then show up other div. Thanks in advance

**Comment by markcellus** [comment] 2021-03-14 15:31
@Jerit3787 Just checked on that browser and not seeing this error. How are you loading the javascript for the package?

**Comment by Jerit3787** [comment] 2021-03-15 08:28
Hmm maybe an issue with the live-preview plugin that I use in vscode.

**Comment by markcellus** [comment] 2021-03-15 11:28
No problem. I'm going to close this issue for now but feel free to leave a comment once you can reproduce with a code snippet. Thanks!

**Closed by markcellus** 2021-03-15 11:28 UTC
